export const expectedUnits = {
  sugar: "g",
  fiber: "g",
  cholesterol: "mg",
  salt: "g",
  macros: {
    protein: "g",
    carbs: "g",
    calories: "kcal",
    fats: {
      total: "g",
      unsaturated: "g",
      saturated: "g",
    },
  },
  micros: {
    vitamins: {
      vitaminA: "mcg",
      vitaminC: "mg",
      vitaminD: "mcg",
      vitaminE: "mg",
      vitaminK: "mcg",
      vitaminB1: "mg",
      vitaminB2: "mg",
      vitaminB3: "mg",
      vitaminB5: "mg",
      vitaminB6: "mg",
      folicAcid: "mcg",
      vitaminB12: "mcg",
      choline: "mg",
      biotin: "mcg",
    },
    minerals: {
      calcium: "mg",
      chloride: "mg",
      chromium: "mcg",
      copper: "mg",
      fluoride: "mcg",
      iodine: "mcg",
      iron: "mg",
      magnesium: "mg",
      manganese: "mg",
      molybdenum: "mcg",
      phosphorus: "mg",
      potassium: "mg",
      selenium: "mcg",
      sodium: "mg",
      zinc: "mg",
    },
  },
};
